-- =====================================================================
-- Projet 3 — API de Conversion de Devises
-- V1 : schéma initial
--
-- Les montants et les taux sont en NUMERIC (décimal exact) et non en
-- DOUBLE PRECISION : une valeur monétaire ne doit jamais être stockée en
-- virgule flottante binaire, qui ne représente pas exactement 0,10 et
-- accumule des écarts au fil des calculs.
-- =====================================================================

-- Dernier taux connu par couple de devises : sert de repli lorsque
-- le fournisseur externe est injoignable.
CREATE TABLE exchange_rates (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_currency VARCHAR(3)      NOT NULL,
    to_currency   VARCHAR(3)      NOT NULL,
    rate          NUMERIC(19, 10) NOT NULL,
    expires_at    TIMESTAMP(6),
    created_at    TIMESTAMP(6),
    updated_at    TIMESTAMP(6),
    CONSTRAINT uk_exchange_rates_pair UNIQUE (from_currency, to_currency)
);

-- Journal des conversions effectuées (historique exposé par l'API).
CREATE TABLE conversion_history (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_currency VARCHAR(3)      NOT NULL,
    to_currency   VARCHAR(3)      NOT NULL,
    amount_from   NUMERIC(19, 4)  NOT NULL,
    amount_to     NUMERIC(19, 4)  NOT NULL,
    rate          NUMERIC(19, 10) NOT NULL,
    source        VARCHAR(20)     NOT NULL,
    created_at    TIMESTAMP(6)
);

-- L'historique est toujours lu du plus récent au plus ancien.
CREATE INDEX idx_conversion_history_created_at ON conversion_history (created_at DESC);
